-- Create Banners Table
CREATE TABLE IF NOT EXISTS public.banners (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    image_url text not null,
    target_path text, -- e.g. /pages/album-detail/index?album=Mario
    is_active boolean default true,
    sort_order int default 0
);

-- Enable RLS
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.banners FOR SELECT USING (true);

-- Insert Sample Data (using existing covers if possible, or placeholders)
INSERT INTO public.banners (title, image_url, target_path, sort_order)
VALUES 
    ('🔥 热门：超级玛丽', 'https://cdn.tewan.club/audios/%E8%B6%85%E7%BA%A7%E7%8E%9B%E4%B8%BD/cover.jpg', '/pages/album-detail/index?album=%E8%B6%85%E7%BA%A7%E7%8E%9B%E4%B8%BD', 1),
    ('🤖 推荐：变形金刚', 'https://cdn.tewan.club/audios/%E5%8F%98%E5%BD%A2%E9%87%91%E5%88%9A/cover.jpg', '/pages/album-detail/index?album=%E5%8F%98%E5%BD%A2%E9%87%91%E5%88%9A', 2);
